apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-backend-ingress
  namespace: myapp-dev
spec:
  rules:
    - host: api.myapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myapp-backend-service
                port:
                  number: 4000
