apiVersion: v1
kind: Service
metadata:
  name: myapp-backend-service
  namespace: myapp-dev
spec:
  selector:
    app: myapp-backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
