apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  namespace: myapp-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      labels:
        app: myapp-frontend
    spec:
      containers:
        - name: myapp-frontend
          image: ghcr.io/huynhdinhhung/myapp-frontend:c16bfc6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
